"""
AI Assistant — uses Azure AI Foundry with Sentinel MCP tools.
Ported for SOC Dashboard: uses config_manager + sentinel_kql.
"""

import base64
import json
import logging

from azure.ai.projects import AIProjectClient
from azure.identity import ClientSecretCredential
from openai import AzureOpenAI

from config_manager import get_config
from sentinel_kql import run_kql

log = logging.getLogger(__name__)

# Scope required by Microsoft Sentinel MCP servers
SENTINEL_MCP_SCOPE = '4500ebfb-89b6-4b14-a480-7f749797bfcd/.default'

SENTINEL_MCP_SERVERS = [
    {
        'type': 'mcp',
        'server_label': 'sentinel-data-exploration',
        'server_url': 'https://sentinel.microsoft.com/mcp/data-exploration',
        'require_approval': 'never',
        'auth_type': 'sp',
    },
    {
        'type': 'mcp',
        'server_label': 'sentinel-triage',
        'server_url': 'https://sentinel.microsoft.com/mcp/triage',
        'require_approval': 'never',
        'auth_type': 'user',
    },
]

AGENT_INSTRUCTIONS = """\
You are a senior SOC analyst AI agent embedded in a security dashboard.
You have access to Microsoft Sentinel via two MCP tool servers.

DATA LAKE tools (long-range KQL — full workspace history):
- **query_lake** — Run KQL queries against a Sentinel Log Analytics workspace.
- **search_tables** — Discover available tables and their schemas.
- **list_sentinel_workspaces** — List available Sentinel workspaces.

TRIAGE tools (Defender XDR — last 30 days, entity drill-down):
- **ListIncidents** — List Defender XDR incidents (filter by severity, status, date, assignee).
- **GetIncidentById** — Get a single incident with all correlated alerts and metadata.
- **ListAlerts** — List security alerts (filter by date, severity, status).
- **GetAlertByID** — Get full alert details including evidence entities.
- **RunAdvancedHuntingQuery** — Run KQL via Advanced Hunting (≤30d, Defender tables).
- **FetchAdvancedHuntingTablesOverview** — List available Advanced Hunting table names + descriptions.
- **FetchAdvancedHuntingTablesDetailedSchema** — Get column schemas for specific tables. ALWAYS call before RunAdvancedHuntingQuery.
- **GetDefenderMachine** — Device details: OS, health, risk score, exposure level.
- **GetDefenderMachineAlerts** — All alerts for a device.
- **GetDefenderMachineLoggedOnUsers** — Accounts that signed in to a device.
- **GetDefenderMachineVulnerabilities** — CVEs discovered on a device.
- **GetDefenderFileInfo** — File details: hashes, size, publisher, cert, prevalence.
- **GetDefenderFileStatistics** — Org-wide file prevalence (device count).
- **GetDefenderFileAlerts** — Alerts generated by a file.
- **GetDefenderFileRelatedMachines** — Devices that encountered a file.
- **GetDefenderIpAlerts** — Alerts related to an IP address.
- **GetDefenderIpStatistics** — Device count that communicated with an IP.
- **FindDefenderMachineByIp** — Devices that communicated with an internal IP ±15 min of a given timestamp. Required params: ipAddress + timestamp.
- **ListDefenderInvestigations** — List automated investigation cases.
- **GetDefenderInvestigation** — Details of a specific automated investigation.
- **ListDefenderIndicators** — Tenant IOCs (file hash, domain, IP) with type/action/severity filters.
- **ListUserRelatedAlerts** — Alerts associated with a user account (by user ID).
- **ListUserRelatedMachines** — Devices where a user has active sessions.
- **ListDefenderMachinesByVulnerability** — Devices affected by a specific CVE.
- **ListDefenderVulnerabilitiesBySoftware** — Vulnerabilities affecting specific software on a device.
- **ListDefenderRemediationActivities** — Remediation tasks with status/device filters.
- **GetDefenderRemediationActivity** — Details of a specific remediation task.

Tool routing — which server to use:
- **Data Lake** for: KQL over full history (>30d), Sentinel-specific tables (SecurityIncident, SecurityAlert, AADUserRiskEvents, SentinelHealth, ThreatIntelligenceIndicator), workspace-level analytics.
- **Triage** for: Defender XDR incident/alert detail, entity drill-down (machines, files, IPs, users), Advanced Hunting ≤30d, automated investigation status, TI indicators.
- When investigating an incident: start with Data Lake for the Sentinel view (SecurityIncident/SecurityAlert), then pivot to Triage for Defender entity details.
- **IncidentNumber** (Sentinel) ≠ Defender XDR ID. Use **ProviderIncidentId** from SecurityIncident to look up incidents in Triage/Graph.

CRITICAL routing rules — follow these exactly:
- "top/highest severity incidents" → Data Lake query_lake with SecurityIncident table. NEVER use Triage ListIncidents or RunAdvancedHuntingQuery for this — SecurityIncident only exists in Data Lake.
- "suspicious sign-ins", "failed logins" → Data Lake query_lake with SigninLogs table.
- "threat summary", "alert trends" → Data Lake query_lake with SecurityAlert table.
- "top alert IPs" → Data Lake query_lake with SecurityAlert + Entity extraction.
- "unassigned incidents" → Data Lake query_lake with SecurityIncident | where Owner.assignedTo == "".
- "brute force check" → Data Lake query_lake with SigninLogs | where ResultType != 0.
- Only use Triage tools when you need Defender XDR entity details (machine info, file hashes, CVEs) or when explicitly asked about Defender/XDR data.
- When a query fails, retry with Data Lake query_lake — do not give up after one attempt.

When an analyst asks a security question:
1. Use search_tables to discover relevant tables if unsure of the schema.
2. Construct a KQL query and execute it with query_lake.
3. For entity drill-down, use the appropriate Triage tool.
4. Analyze the results and provide a clear, actionable summary.

Rules:
- Always limit results with `take` or `top` (max 50 rows).
- Use `ago()` for time filters. Default to last 7 days if no time range specified.
- Never modify or delete data — read-only queries only.
- When analyzing incidents, correlate alerts, entities, and timelines.
- Provide MITRE ATT&CK mapping when identifying attack patterns.
- Keep explanations concise — analysts are technical.
- When you execute a KQL query, include it in your response inside a ```kql block.

Evidence-based analysis — STRICT:
- Base ALL findings on data returned by tools. Never invent, assume, or extrapolate.
- If a query returns 0 results, state: "No [event type] found in [time range]" — never say "likely" without evidence.
- If a field is null or missing, report as "Unknown" — never fabricate values.
- When data is partial, state what WAS found and what COULD NOT be verified.
- Risk levels require cited evidence:
  - High: cite ≥2 concrete findings (e.g., "AbuseIPDB score 95 + 47 failed logins in 1 hour")
  - Medium: cite ≥1 finding with context (e.g., "New IP not in 90-day baseline")
  - Low: explain why low despite investigation
- After every analysis section, confirm what was checked even if nothing was found.
- Never use phrases like "typically", "usually", "in most environments" as substitutes for real data.

KQL pitfalls:
- SecurityAlert.Status is IMMUTABLE (always "New") — join SecurityIncident for real status.
- SecurityIncident.AlertIds contains GUIDs, not entity names — never filter by name.
- **AlertIds join key is dynamic — CRITICAL**: After `mv-expand AlertId = AlertIds`, AlertId is
  STILL dynamic. MUST add `| extend AlertId = tostring(AlertId)` before any join or `in` filter.
  Correct: mv-expand AlertId = AlertIds | extend AlertId = tostring(AlertId)
           | join kind=leftouter (SecurityAlert | project SystemAlertId, ...) on $left.AlertId == $right.SystemAlertId
- SigninLogs dynamic fields (DeviceDetail, LocationDetails, Status): always use parse_json() before dot-access.
- IncidentNumber is Sentinel-local — use ProviderIncidentId for Defender XDR / Graph API.
- AADRiskySignIns does not exist in Data Lake — use AADUserRiskEvents instead.
- SecurityEvent, CommonSecurityLog, Syslog, OfficeActivity do NOT exist — never query them.
- Use AlertSeverity (not Severity) and ProviderName (not ProductName) for SecurityAlert.
- Never project an alias named `Type` — it collides with a reserved column. Use `EventType` instead.
- SecurityAlert.Entities is a JSON **string**, not dynamic. Always: `mv-expand Entity = parse_json(Entities)`. Never bare `mv-expand Entities`.
- SecurityAlert does NOT have `CreatedTimeUtc` — that column belongs to SecurityIncident. For alert timestamps use `TimeGenerated` (ingest) or `StartTime`/`EndTime` (alert window). Projecting `CreatedTimeUtc` from a SecurityAlert subquery causes: 'Failed to resolve scalar expression named CreatedTimeUtc'.
- `LastModifiedTimeUtc` does NOT exist in any Sentinel table. SecurityIncident uses `LastModifiedTime` (no Utc suffix).

Investigation playbooks — follow these step-by-step when the analyst's question matches:

USER INVESTIGATION (triggers: "investigate user", "check user", UPN/email):
1. SigninLogs — last 7d: summarize by IPAddress, ResultType, AppDisplayName. Note failures.
2. AADNonInteractiveUserSignInLogs — same period: check for token-based access patterns.
3. New IPs: compare 7d IPs against 90d baseline (leftanti join). Flag any new.
4. AuditLogs — filter by tostring(InitiatedBy) has '<UPN>': password changes, role assignments.
5. SecurityAlert — filter by Entities has '<UPN>': any alerts involving the user.
6. SecurityIncident — join from alerts above to get real Status/Classification.
7. Triage pivot: ListUserRelatedAlerts + ListUserRelatedMachines for Defender-side context.
8. Summarize: risk level (High/Medium/Low) with cited evidence. List what was checked.

INCIDENT TRIAGE (triggers: "investigate incident", "triage incident", incident number):
1. SecurityIncident — get detail: Title, Severity, Status, Classification, AlertIds, ProviderIncidentId.
2. SecurityAlert — join via AlertIds using: mv-expand AlertId = AlertIds | extend AlertId = tostring(AlertId)
   then join SecurityAlert on $left.AlertId == $right.SystemAlertId. ALWAYS cast to tostring before join.
3. Entity extraction — mv-expand Entity = parse_json(Entities) from alerts, group by Type (account, ip, host).
4. Triage pivot: GetIncidentById(ProviderIncidentId) for Defender XDR enrichment.
5. For each machine entity: GetDefenderMachine + GetDefenderMachineLoggedOnUsers + GetDefenderMachineVulnerabilities.
6. Related incidents — find same ProviderName or overlapping entities in last 30d.
7. Summarize: attack narrative, MITRE tactics, affected entities, recommended next steps.

IP INVESTIGATION (triggers: "investigate IP", "is this IP", "check IP"):
1. SigninLogs — filter by IPAddress: who signed in from this IP, how many times, which apps.
2. SecurityAlert — filter by Entities has '<IP>': any alerts involving it.
3. ThreatIntelligenceIndicator — check for TI matches on this IP.
4. Triage pivot: GetDefenderIpAlerts + GetDefenderIpStatistics + FindDefenderMachineByIp (requires timestamp — use current UTC time).
5. If available, mention the analyst can use /api/ip/enrich/<IP> for external threat intel.
6. Summarize: reputation assessment with evidence. Flag if new IP not in 90d baseline.

ALERT ANALYSIS (triggers: "analyze alerts", "alert trends", "top alerts"):
1. SecurityAlert — summarize count by AlertName, AlertSeverity, Tactics in requested period.
2. SecurityIncident — join to check which alerts are in open vs closed incidents.
3. Trend: compare current period vs prior period (e.g., 7d vs prior 7d).
4. Summarize: top threats, trend direction, any unresolved high-severity items.
"""

SYSTEM_PROMPT = """\
You are a SOC analyst AI assistant embedded in a security dashboard.
You help analysts query and understand Microsoft Sentinel data.

When the user asks a security question:
1. Generate a KQL query to answer it.
2. Return your response in this exact format:

```kql
<your KQL query here>
```

**Explanation:** <brief explanation of what the query does and what the results mean>

Rules:
- Only query tables that exist in this Sentinel workspace:
  SecurityIncident, SecurityAlert, ThreatIntelligenceIndicator, SigninLogs,
  AADNonInteractiveUserSignInLogs, AADUserRiskEvents, AuditLogs.
- Tables that do NOT exist (never use these): SecurityEvent, Heartbeat,
  CommonSecurityLog, Syslog, AADRiskySignIns, OfficeActivity.
- SecurityAlert uses AlertSeverity (not Severity) and ProviderName (not ProductName).
- Always limit results with `take` or `top` (max 50 rows) to avoid large payloads.
- Use `summarize` for aggregations when appropriate.
- Use `ago()` for time filters. Default to last 7 days if no time range specified.
- Never modify or delete data — read-only queries only.
- If the user asks something you cannot answer with KQL, explain why.
- Keep explanations concise — analysts are technical.

Evidence-based analysis — STRICT:
- Base ALL findings on query results. Never invent data or assume typical patterns.
- 0 results = state "No [event type] found" — never fabricate or speculate.
- Null/missing fields = "Unknown" — never guess.
- After each analysis section, confirm what was checked even if clean.

KQL pitfalls:
- SecurityAlert.Status is IMMUTABLE (always "New") — join SecurityIncident for real status.
- SecurityIncident.AlertIds contains GUIDs — never filter by entity name.
- **AlertIds join key is dynamic — CRITICAL**: After `mv-expand AlertId = AlertIds`, AlertId is
  STILL dynamic type. You MUST add `| extend AlertId = tostring(AlertId)` immediately
  after the mv-expand, before any join.
  Correct pattern:
    SecurityIncident
    | mv-expand AlertId = AlertIds
    | extend AlertId = tostring(AlertId)
    | join kind=leftouter (
        SecurityAlert | project SystemAlertId, AlertName, AlertSeverity
      ) on $left.AlertId == $right.SystemAlertId
- SigninLogs dynamic fields: always parse_json() before dot-access.
- IncidentNumber ≠ Defender XDR ID — use ProviderIncidentId for cross-platform lookups.
- SecurityEvent, CommonSecurityLog, Syslog do NOT exist in this workspace — never query them.
- Use AlertSeverity (not Severity) and ProviderName (not ProductName) for SecurityAlert.
- Never use `Type` as a projected alias — it's a reserved column name. Use `EventType` instead.
- SecurityAlert.Entities is a JSON **string**, not dynamic. Always: `mv-expand Entity = parse_json(Entities)`. Never bare `mv-expand Entities`.
- SecurityAlert does NOT have `CreatedTimeUtc` — that column belongs to SecurityIncident. For alert timestamps use `TimeGenerated` (ingest) or `StartTime`/`EndTime` (alert window).
- `LastModifiedTimeUtc` does NOT exist in any Sentinel table. SecurityIncident uses `LastModifiedTime` (no Utc suffix).
"""


# ── Helpers ─────────────────────────────────────────────────────────────────

def _decode_jwt_claims(token: str) -> dict:
    """Decode JWT payload (no signature verification — for logging only)."""
    try:
        payload = token.split('.')[1]
        padding = 4 - len(payload) % 4
        payload += '=' * padding
        return json.loads(base64.urlsafe_b64decode(payload))
    except Exception:
        return {}


def _get_credential() -> ClientSecretCredential:
    tenant = get_config('TENANT_ID') or ''
    client = get_config('CLIENT_ID') or ''
    secret = get_config('CLIENT_SECRET') or ''
    if not all([tenant, client, secret]):
        raise RuntimeError('Missing TENANT_ID, CLIENT_ID, or CLIENT_SECRET in config')
    return ClientSecretCredential(
        tenant_id=tenant,
        client_id=client,
        client_secret=secret,
    )


def _foundry_token_provider() -> str:
    """Token provider callback for AzureOpenAI (direct completion fallback)."""
    cred = _get_credential()
    token = cred.get_token('https://cognitiveservices.azure.com/.default')
    return token.token


def _get_direct_client() -> AzureOpenAI:
    """Direct OpenAI client (fallback when agent is unavailable)."""
    endpoint = get_config('FOUNDRY_ENDPOINT')
    if not endpoint:
        raise RuntimeError('FOUNDRY_ENDPOINT not configured')
    return AzureOpenAI(
        azure_endpoint=endpoint,
        azure_ad_token_provider=_foundry_token_provider,
        api_version='2024-12-01-preview',
    )


# ── Agent path (MCP tools) ─────────────────────────────────────────────────

def ask_agent(
    question: str,
    history: list[dict] | None = None,
    *,
    user_token: str | None = None,
    triage_token: str | None = None,
    deployment: str | None = None,
) -> dict:
    """Send a question to the Foundry Responses API with Sentinel MCP tools.

    Falls back to direct completion if MCP is unavailable.
    `deployment` overrides FOUNDRY_DEPLOYMENT for this call (model-tier routing).
    Returns {"answer", "kql", "results", "tool_calls", "error"}
    """
    project_endpoint = get_config('FOUNDRY_PROJECT_ENDPOINT')
    deployment = deployment or get_config('FOUNDRY_DEPLOYMENT') or ''
    if not project_endpoint:
        return ask_assistant(question, history)

    try:
        credential = _get_credential()

        # SP token for Data Lake server
        sp_token = credential.get_token(SENTINEL_MCP_SCOPE).token
        sp_claims = _decode_jwt_claims(sp_token)
        log.debug('Data Lake SP token claims: %s', sp_claims)
        if triage_token:
            triage_claims = _decode_jwt_claims(triage_token)
            log.debug('Triage delegated token claims: %s', triage_claims)

        # Build MCP tools — SP token for Data Lake, triage token for Triage
        tools = []
        for server in SENTINEL_MCP_SERVERS:
            auth_type = server.get('auth_type', 'sp')
            if auth_type == 'user':
                if not triage_token:
                    log.info('Triage MCP skipped — no delegated triage token available')
                    continue
                token = triage_token
                log.info('Triage MCP included with delegated triage token')
            else:
                token = sp_token
            tool_config = {k: v for k, v in server.items() if k != 'auth_type'}
            tool_config['authorization'] = token
            tools.append(tool_config)

        client = AIProjectClient(
            endpoint=project_endpoint,
            credential=credential,
        )
        oai = client.get_openai_client()

        # Build conversation input
        messages = []
        for msg in (history or []):
            messages.append({'role': msg['role'], 'content': msg['content']})
        messages.append({'role': 'user', 'content': question})

        # Build workspace-aware instructions
        ws_instructions = AGENT_INSTRUCTIONS
        try:
            from database import get_workspaces
            ws_list = get_workspaces()
            if ws_list:
                ws_lines = '\n'.join(
                    f"  - {w['name']}: {w['workspace_id']}" + (' (default)' if w['is_default'] else '')
                    for w in ws_list
                )
                ws_instructions += f"\n\nAvailable Sentinel workspaces:\n{ws_lines}\nUse the default workspace for query_lake unless the analyst specifies another."
        except Exception:
            pass

        def _invoke(tool_list: list) -> dict:
            resp = oai.responses.create(
                model=deployment,
                instructions=ws_instructions,
                input=messages,
                tools=tool_list,
                timeout=90,
            )
            item_types = [getattr(i, 'type', 'unknown') for i in resp.output]
            log.info('Agent response items: %s', item_types)
            # Match any call-shaped output item: the Responses API emits
            # 'tool_call', 'mcp_call' and 'function_call' depending on version,
            # and an exact 'tool_call' test silently reports zero tool use.
            calls = [
                getattr(i, 'name', '') or str(getattr(i, 'type', ''))
                for i in resp.output
                if 'call' in str(getattr(i, 'type', ''))
            ]
            calls = [c for c in calls if c]
            if calls:
                log.info('MCP tools called: %s', calls)
            answer = ''
            for item in resp.output:
                if getattr(item, 'type', '') == 'message':
                    for part in (getattr(item, 'content', None) or []):
                        text = getattr(part, 'text', None)
                        if text:
                            answer += text
            log.info('Agent answer length: %d chars', len(answer))
            kql = None
            if '```kql' in answer:
                try:
                    start = answer.index('```kql') + 6
                    end = answer.index('```', start)
                    kql = answer[start:end].strip()
                except ValueError:
                    pass
            return {'answer': answer, 'kql': kql, 'results': None,
                    'tool_calls': calls, 'error': None}

        def _invoke_with_fallback(tool_list: list) -> dict:
            try:
                return _invoke(tool_list)
            except Exception as exc:
                exc_str = str(exc)
                is_401 = '401' in exc_str or 'Unauthorized' in exc_str
                if not is_401:
                    raise

                log.warning('MCP 401 detail: %s', exc_str[:500])
                triage_401 = 'sentinel-triage' in exc_str
                datalake_401 = 'sentinel-data-exploration' in exc_str
                has_triage = any(t.get('server_label') == 'sentinel-triage' for t in tool_list)
                has_datalake = any(t.get('server_label') == 'sentinel-data-exploration' for t in tool_list)

                if triage_401 and has_triage and has_datalake:
                    log.warning('Triage MCP 401 — retrying with Data Lake tools only')
                    return _invoke([t for t in tool_list if t.get('server_label') != 'sentinel-triage'])
                if datalake_401 and has_datalake and has_triage:
                    log.warning('Data Lake MCP 401 — retrying with Triage tools only')
                    return _invoke([t for t in tool_list if t.get('server_label') != 'sentinel-data-exploration'])

                log.warning('All MCP servers unavailable — retrying agent with no tools')
                return _invoke([])

        result = _invoke_with_fallback(tools)
        client.close()
        return result

    except Exception as exc:
        log.warning('Agent invocation failed (%s), falling back to direct completion', exc)
        return ask_assistant(question, history)


# ── KQL repair ──────────────────────────────────────────────────────────────

_KQL_COLUMN_FIXES = {
    'CreatedTimeUtc': 'TimeGenerated',
    'LastModifiedTimeUtc': 'LastModifiedTime',
}


def _repair_kql(kql: str) -> str:
    """Apply known column-name fixes to LLM-generated KQL before execution."""
    for bad, good in _KQL_COLUMN_FIXES.items():
        if bad in kql:
            log.warning("KQL repair: replacing '%s' with '%s'", bad, good)
            kql = kql.replace(bad, good)
    return kql


# ── Direct completion fallback ──────────────────────────────────────────────

def ask_assistant(question: str, history: list[dict] | None = None) -> dict:
    """Fallback: direct OpenAI completion with KQL auto-execute.

    Returns {"answer": str, "kql": str|None, "results": list|None, "error": str|None}
    """
    deployment = get_config('FOUNDRY_DEPLOYMENT')
    if not deployment:
        return {'answer': '', 'kql': None, 'results': None, 'tool_calls': [],
                'error': 'AI Assistant not configured — set FOUNDRY_ENDPOINT and FOUNDRY_DEPLOYMENT in Settings.'}

    messages: list = [{'role': 'system', 'content': SYSTEM_PROMPT}]
    for msg in (history or []):
        messages.append({'role': msg['role'], 'content': msg['content']})
    messages.append({'role': 'user', 'content': question})

    client = _get_direct_client()
    completion = client.chat.completions.create(
        model=deployment,
        messages=messages,
        max_completion_tokens=2048,
    )

    answer = completion.choices[0].message.content or ''

    kql = None
    results = None
    error = None
    if '```kql' in answer:
        try:
            start = answer.index('```kql') + 6
            end = answer.index('```', start)
            kql = answer[start:end].strip()
        except ValueError:
            pass

        if kql:
            kql = _repair_kql(kql)
            log.info('Auto-executing generated KQL:\n%s', kql)
            try:
                results = run_kql(kql)
            except Exception as exc:
                log.warning('Generated KQL failed: %s', exc)
                error = 'Generated KQL query failed — check server logs'

    # The direct path counts as retrieval only when the generated KQL ran.
    return {'answer': answer, 'kql': kql, 'results': results,
            'tool_calls': ['run_kql'] if results is not None else [],
            'error': error}
